USE [master]
GO

/****** Object:  Database [SportsStore]    Script Date: 6/12/2016 11:59:47 AM ******/
CREATE DATABASE [SportsStore]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'EFDbContext.mdf', FILENAME = N'D:\vs2015\ASPNET\SportsStore.WebUI\App_Data\EFDbContext.mdf' , SIZE = 3136KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'EFDbContext_log.ldf', FILENAME = N'D:\vs2015\ASPNET\SportsStore.WebUI\App_Data\EFDbContext_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [SportsStore] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SportsStore].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [SportsStore] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [SportsStore] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [SportsStore] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [SportsStore] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [SportsStore] SET ARITHABORT OFF 
GO

ALTER DATABASE [SportsStore] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [SportsStore] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [SportsStore] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [SportsStore] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [SportsStore] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [SportsStore] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [SportsStore] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [SportsStore] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [SportsStore] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [SportsStore] SET  ENABLE_BROKER 
GO

ALTER DATABASE [SportsStore] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [SportsStore] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [SportsStore] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [SportsStore] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [SportsStore] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [SportsStore] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [SportsStore] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [SportsStore] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [SportsStore] SET  MULTI_USER 
GO

ALTER DATABASE [SportsStore] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [SportsStore] SET DB_CHAINING OFF 
GO

ALTER DATABASE [SportsStore] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [SportsStore] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [SportsStore] SET  READ_WRITE 
GO

